#!/bin/bash

# lib
mkdir -p /usr/local/lib/mailmark
cp -r template/ /usr/local/lib/mailmark
cp uninstall /usr/local/lib/mailmark

# bin
cp mailmark.py /usr/local/bin
chmod +x /usr/local/bin/mailmark.py